videoserver: modified init.d script to be compatible with videosockserver

diff --git a/videosink/scripts/videoserver-single b/videosink/scripts/videoserver-single
--- a/videosink/scripts/videoserver-single
+++ b/videosink/scripts/videoserver-single
@@ -22,13 +22,13 @@ DESC="videoserver service (single instance)"
 DAEMON=/usr/local/videoserver/videoserver_testing.sh
 #DAEMON=/usr/local/videoserver/workerserver.sh
 #DAEMON_ARGS="--options args"
-PTU_ID=${2}
-SESSION_ID="t0${PTU_ID}"
+PTU_MAC=${2}
+SESSION_ID="t0${PTU_MAC}"
 [ -n "$3" ] && SESSION_ID=${3}
-NAME=videoserver-${PTU_ID}
-LOGFILENAME="/var/log/videoserver/"`date +"%y%m%d"`.${PTU_ID}.log
+NAME=videoserver-${PTU_MAC}
+LOGFILENAME="/var/log/videoserver/"`date +"%y%m%d"`.${PTU_MAC}.log
 DAEMON_ARGS="10:00:00:00:00:00 0 t01 ${LOGFILENAME}"
-PIDFILE=/var/run/videoserver/$NAME-$PTU_ID.pid
+PIDFILE=/var/run/videoserver/$NAME.pid
 SCRIPTNAME=/etc/init.d/$NAME
 USERID=chpap:chpap
 USERID=$USER:$USER
@@ -38,7 +38,7 @@ CONFFILE=/etc/videostream.conf.d/videoserver.conf
 [ -x "$DAEMON" ] || exit 0
 read_conf()
 {
-	grep "^$2 " $1 | sed -e "s/^$2 //"
+	grep " $2 " $1 | sed -e "s/^.*$2 //"
 }
 
 # Load the VERBOSE setting and other rcS variables
@@ -52,14 +52,14 @@ VERBOSE=yes
 
 # Read configuration variable file if it is present
 if [ -r "$CONFFILE" ] ;then
-	DAEMON_ARGS=`read_conf "$CONFFILE" "$PTU_ID"` 
+	SLOT=`read_conf "$CONFFILE" "$PTU_MAC"` 
 #	echo $DAEMON_ARGS
-	if [ -z "$DAEMON_ARGS" ];then
-		log_daemon_msg "PTU ID $PTU_ID not found in configuration file $CONFFILE" && log_end_msg 1 
+	if [ -z "$SLOT" ];then
+		log_daemon_msg "PTU ID $PTU_MAC not found in configuration file $CONFFILE" && log_end_msg 1 
 		exit 1
 	fi
 	
-	DAEMON_ARGS="$DAEMON_ARGS $SESSION_ID $LOGFILENAME"
+	DAEMON_ARGS="$PTU_MAC $SLOT $SESSION_ID $LOGFILENAME"
 fi
 
 #
@@ -98,13 +98,14 @@ do_stop()
 	#   1 if daemon was already stopped
 	#   2 if daemon could not be stopped
 	#   other if a failure occurred
-	[ -f "$PIDFILE"  ] || return 2
+	[ -f "$PIDFILE"  ] || return 1
 	PGID=`ps --no-heading -p $(cat $PIDFILE) -o "%r"| awk '{print $1}'`
 	echo $PGID
+	[ -z "$PGID"  ] || return 1
 	kill -INT -${PGID}
 #	sleep 5
 #	kill -KILL -${PGID}
-	RETVAL=1
+	RETVAL=0
 #	start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --name $NAME
 #	RETVAL="$?"
 #	[ "$RETVAL" = 2 ] && return 2
